// Code generated by i18n error platform, please DO NOT EDIT.
package query

import (
	"errors"
)

var (
	ErrMapUndefined       error = errors.New(" map undefined")    //
	ErrFormatInvalid      error = errors.New(" format invalid")   // 格式有误
	ErrMapKeyInvalid      error = errors.New(" map key invalid")  // key中有非法字符
	ErrMapOperatorInvalid error = errors.New(" operator invalid") // 比较符非法
	ErrMapValMapMultiple  error = errors.New(" val-map invalid")  // map表示的val只有一对key-val
	ErrMapDeepOutOf       error = errors.New(" map deep out of")  // map层太深
)
